---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

# Debian family OSes also have an /etc/timezone file.
- name: Set timezone in /etc/timezone file.
  template:
    src: timezone.j2
    dest: /etc/timezone
    force: yes
  when: ansible_os_family == 'Debian'

- name: Install NTP (RedHat).
  yum: name=ntp state=installed
  when: ansible_os_family == 'RedHat'

- name: Install NTP (Debian).
  apt: name=ntp state=installed
  when: ansible_os_family == 'Debian'

- name: Install NTP (FreeBSD).
  pkgng: name=ntp state=present
  when: ansible_os_family == 'FreeBSD'

- name: Ensure NTP is running and enabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: no
  when: not ntp_enabled

- name: Generate ntp.conf file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  # notify: restart ntp
  register: ntp_conf
  when: ntp_manage_config

- name: Allow NTP Access in iptables
  iptables_raw:
    name: allow_udp_123
    rules: '-A INPUT -p udp -m udp --dport 123 -j ACCEPT'
  register: ip_tables

- name: restart ntp
  service: 
    name: "{{ ntp_daemon }}"
    state: restarted"
  when: ntp_conf.changed

- name: restart iptables
  service: 
    name: iptables
    state: restarted
  when: ip_tables.changed

