- hosts: under	
  # become: yes
  gather_facts: true
  roles:
   - { role: network,tags: ['prep'] }
   - { role: fix_dns,tags: ['prep'] }
   - { role: hostconf,tags: ['prep'] }
   - { role: fix_dns,tags: ['prep'] }
   - { role: system-update,tags: ['prep'] }
   - { role: fix_dns,tags: ['prep'] }
   - { role: fix_dns,tags: ['prep'] }
   - { role: undercloud, tags: ['undercloud'] }
   - fix_dns
   - { role: overcloud_nodes, tags: ['overcloud','overcloud_nodes'] }
   - { role: overcloud_introspection, tags: ['overcloud','overcloud_introspection'] }
   - { role: overcloud_storage, tags: ['overcloud','overcloud_storage'] }
   - { role: overcloud_network, tags: ['overcloud','overcloud_network'] }
   - { role: overcloud_deploy, tags: ['overcloud','overcloud_deploy'] }
