- hosts: under	
  gather_facts: true

  roles:
    - name: Define and Configure Undercloud Network
      role: network
      tags:
        - prep

    - name: Fix Lab DNS /etc/resolv.conf
      role: fix_dns
      tags:
        - prep

    - name: Perform Undercloud Host Configuration
      role: hostconf
      tags:
        - prep

    - name: Configure NTP Daemon
      role: ntp
      tags:
        - prep

    - name: Fix Lab DNS /etc/resolv.conf
      role: fix_dns
      tags:
        - prep

    - name: Perform a System Update on the Undercloud
      role: system-update
      tags:
        - prep

    - name: Configure and Deploy the Undercloud
      role: undercloud
      tags:
        - undercloud

    - name: Fix Lab DNS /etc/resolv.conf
      role: fix_dns
      tags:
        - overcloud

    - name: Configure Overcloud Nodes
      role: overcloud_nodes
      tags:
        - overcloud
        - overcloud_nodes

    - name: Prepare and Run Overcloud Introspection
      role: overcloud_introspection
      tags:
        - overcloud
        - overcloud_introspection

    - name: Define Overcloud Storage
      role: overcloud_storage
      tags:
        - overcloud
        - overcloud_storage

    - name: Define Overcloud Network
      role: overcloud_network
      tags:
        - overcloud
        - overcloud_network

    - name: Deploy the Overcloud
      role: overcloud_deploy
      tags:
        - overcloud
        - overcloud_deploy
