---
# tasks file for roles/overcloud_nodes


- block:

  - name: Configure Boot
    shell: openstack baremetal configure boot
    register: configure_boot

  - name: Debug Configure Boot
    debug:
      var: configure_boot
      verbosity: 2

  - name: Run Node Introspection
    shell: openstack baremetal introspection bulk start
    register: node_introspection

  - name: Debug Node Introspection
    debug:
      var: node_introspection.stdout_lines
      verbosity: 2

  - name: Tag Nodes
    shell: ironic node-update {{ item.name }} add properties/capabilities='profile:{{ item.profile }},boot_option:local'
    register: tag_nodes
    with_items: "{{ nodes }}"

  - name: Debug Tag Nodes
    debug:
      var: tag_nodes
      verbosity: 2

  - name:  Get Overcloud Profiles List
    shell: openstack overcloud profiles list
    register: os_profiles_list

  - name: Debug profiles List
    debug:
      var: os_profiles_list.stdout_lines

  - name: Define Nodes Root Disk
    shell: ironic node-update {{ item.name }} add properties/root_device='{% raw %}{{% endraw %}"{{ item.root_device.property }}":"{{ item.root_device.value }}"{% raw %}}{% endraw %}'
    register: root_device
    with_items: "{{ nodes }}"


  environment:
    NOVA_VERSION: "{{ undercloud_rc.NOVA_VERSION }}"
    OS_PASSWORD: "{{ undercloud_password.stdout }}"
    OS_AUTH_URL: "{{ undercloud_rc.OS_AUTH_URL }}"
    OS_USERNAME: "{{ undercloud_rc.OS_USERNAME }}"
    OS_TENANT_NAME: "{{ undercloud_rc.OS_TENANT_NAME }}"
    COMPUTE_API_VERSION: "{{ undercloud_rc.COMPUTE_API_VERSION }}"
    OS_NO_CACHE: "{{ undercloud_rc.OS_NO_CACHE }}"
    OS_CLOUDNAME: "{{ undercloud_rc.OS_CLOUDNAME }}"
    OS_IMAGE_API_VERSION: "{{ undercloud_rc.OS_IMAGE_API_VERSION }}"
