---
- name: Copy Ethernet configuration files
  template: 
    src: ifcfg-eth.j2 
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth{{ item.device_id }}{{ item.vlan_id }}"
  with_items: "{{ networks }}"
  become: true
  register: network_template
  notify:
   - restart network

- name: Debug Ethernet config files
  debug:
    var: network_template
