---
- name: Copy ethernet configuration files
  template: 
    src: ifcfg-eth.j2 
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth{{ item.device_id }}{{ item.vlan_id }}"
  with_items: "{{ networks }}"
  become: true
  notify:
   - restart-network
