---
- name: Copy Ethernet configuration files
  template: 
    src: ifcfg-eth.j2 
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth{{ item.device_id }}{{ item.vlan_id }}"
  with_items: "{{ networks }}"
  become: true
  register: network_template

- name: Debug Ethernet config files
  debug:
    var: network_template
    verbosity: 2

- name: Restart Network
  service:
    name: network
    state: restarted
  when: network_template.changed
  become: true
